import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { detectDevServer } from './detect.ts';

export type PublishTarget = {
  kind: 'static' | 'node' | 'container' | 'unsupported';
  label: string;
  detail: string;
  dockerfile?: string;
};

/**
 * Works out how this project could be shipped. Deliberately conservative: a
 * target is only offered when the project's own files make the shape
 * unambiguous, rather than guessing and generating something that does not run.
 */
export async function detectPublish(dir: string): Promise<PublishTarget> {
  const has = (...files: string[]) => files.some((file) => existsSync(join(dir, file)));

  if (has('Dockerfile')) {
    return { kind: 'container', label: 'Container', detail: 'This project already has a Dockerfile.' };
  }

  const pkg = await readFile(join(dir, 'package.json'), 'utf8')
    .then((text) => JSON.parse(text) as { scripts?: Record<string, string>; dependencies?: Record<string, string> })
    .catch(() => null);

  if (pkg?.scripts?.build) {
    const isServer = Boolean(pkg.dependencies?.express || pkg.dependencies?.fastify || pkg.dependencies?.hono);
    return isServer
      ? {
          kind: 'node',
          label: 'Node server',
          detail: 'Has a build script and a server dependency.',
          dockerfile: nodeServerDockerfile,
        }
      : {
          kind: 'static',
          label: 'Static build',
          detail: 'Has a build script. Publishes whatever `npm run build` emits.',
          dockerfile: staticDockerfile,
        };
  }

  if (has('index.html') && !pkg) {
    return { kind: 'static', label: 'Static site', detail: 'Plain HTML with no build step.' };
  }

  if (await detectDevServer(dir)) {
    return {
      kind: 'unsupported',
      label: 'Not yet',
      detail: 'Kiln does not know how to ship this stack. Add a Dockerfile and it will use that.',
    };
  }

  return { kind: 'unsupported', label: 'Not yet', detail: 'Nothing to publish yet.' };
}

const staticDockerfile = `# Generated by kiln. Adjust freely.
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
`;

const nodeServerDockerfile = `# Generated by kiln. Adjust freely.
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22-alpine
ENV NODE_ENV=production
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/index.js"]
`;

export async function writeDockerfile(dir: string, template: string): Promise<string> {
  const target = join(dir, 'Dockerfile');
  if (existsSync(target)) return target;
  await mkdir(dir, { recursive: true });
  await writeFile(target, template);
  return target;
}
