import { existsSync, readFileSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const CONFIG_NAMES = [
  'vite.config.js',
  'vite.config.mjs',
  'vite.config.ts',
  'vite.config.mts',
  'vite.config.cjs',
];

export type ViteWrap = {
  /** Args to append to the vite invocation. */
  args: string[];
  /** Absolute path of the generated wrapper, for diagnostics. */
  configPath: string;
};

// Repository root, whether this runs from src/ (development) or dist/ (shipped).
const KILN_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

/**
 * Adds Kiln's provenance plugin by wrapping the project's own Vite config
 * rather than editing it.
 *
 * The project is left untouched, so `npm run dev` keeps working normally and
 * nothing breaks when the user moves on. Kiln only runs the wrapped config
 * itself, which is where the element ids come from.
 */
export async function wrapViteConfig(dir: string): Promise<ViteWrap | null> {
  const base = CONFIG_NAMES.map((name) => join(dir, name)).find((path) => existsSync(path));
  if (!base) return null;

  const outFile = join(dir, '.kiln', 'provenance.json');
  const kilnDir = join(dir, '.kiln');
  await mkdir(kilnDir, { recursive: true });

  // Always the compiled entry: a .mjs wrapper cannot import the .ts source.
  const pluginEntry = join(KILN_ROOT, 'dist', 'provenance', 'plugin.js');
  if (!existsSync(pluginEntry)) {
    throw new Error('kiln is not built; run `npm run build`');
  }
  const source = `// Generated by kiln. Not part of your project; safe to delete.
import { mergeConfig } from 'vite';
import base from ${JSON.stringify(base)};
import { provenancePlugin } from ${JSON.stringify(pluginEntry)};

export default mergeConfig(base, {
  plugins: [provenancePlugin({ outFile: ${JSON.stringify(outFile)} })],
});
`;

  const configPath = join(kilnDir, 'vite.config.mjs');
  await writeFile(configPath, source);
  return { args: ['--config', configPath], configPath };
}

/** True when this project is a Vite app, and Kiln can wrap its config. */
export function isVite(dir: string): boolean {
  if (!CONFIG_NAMES.some((name) => existsSync(join(dir, name)))) return false;
  try {
    const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) as {
      devDependencies?: Record<string, string>;
      dependencies?: Record<string, string>;
    };
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };
    return Boolean(deps.vite);
  } catch {
    // No readable package.json: the config file alone is enough of a signal.
    return true;
  }
}