import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { readFileSync, writeFileSync } from 'node:fs';
import { field, log, verdict } from './harness.ts';
import { startDevServer } from '../runtime/manager.ts';
import { createProxy, INJECTED_CLIENT } from '../proxy/server.ts';
import { launchBrowser } from '../capture/browser.ts';
import { createServer } from 'node:http';
import type { ElementRef } from '../provenance/plugin.ts';

const here = dirname(fileURLToPath(import.meta.url));
const fixture = join(here, '..', '..', 'test', 'fixtures', 'jsx-app');
const appFile = join(fixture, 'src', 'App.jsx');
const indexFile = join(fixture, '.kiln', 'provenance.json');

type Snapshot = { version: number; elements: ElementRef[] };

function readIndex(): Snapshot {
  return JSON.parse(readFileSync(indexFile, 'utf8')) as Snapshot;
}

const findButton = (snapshot: Snapshot) =>
  snapshot.elements.find((e) => e.attributes.id === 'submit-btn');

const original = readFileSync(appFile, 'utf8');
const truthLineOf = (source: string) =>
  source.split('\n').findIndex((line) => line.includes('id="submit-btn"')) + 1;

const clientServer = createServer((_, res) => {
  res.writeHead(200, { 'content-type': 'application/javascript' });
  res.end(INJECTED_CLIENT);
});
const clientPort = await new Promise<number>((resolve) => {
  clientServer.listen(0, '127.0.0.1', () => resolve((clientServer.address() as { port: number }).port));
});

// The fixture is rewritten in place below, so restore it on any exit path,
// including a failure during startup.
const restore = () => writeFileSync(appFile, original);
process.on('exit', restore);

let server: Awaited<ReturnType<typeof startDevServer>> | null = null;
let proxy: ReturnType<typeof createProxy> | null = null;
let browser: Awaited<ReturnType<typeof launchBrowser>> | null = null;

try {
  server = await startDevServer({ cwd: fixture, readyTimeoutMs: 90_000 });
  proxy = createProxy({
    host: '127.0.0.1',
    port: server.port,
    clientUrl: `http://127.0.0.1:${clientPort}/client.js`,
  });
  const proxyPort = await proxy.listen(0);
  browser = await launchBrowser();
  await browser.goto(`http://127.0.0.1:${proxyPort}/`);

  const first = readIndex();
  const firstButton = findButton(first);
  const attrFirst = await browser.evaluate<string | null>(
    "document.querySelector('#submit-btn')?.getAttribute('data-kiln-id') ?? null",
  );

  field('index version', first.version);
  field('elements indexed', first.elements.length);
  field('button id', firstButton?.id);
  field('button file', firstButton?.file.split('/').slice(-2).join('/'));
  field('button line', `${firstButton?.line} (truth ${truthLineOf(original)})`);
  field('dom data-kiln-id', attrFirst);
  field('id matches index', attrFirst === firstButton?.id);

  // HMR: a small in-place edit, as a normal turn produces.
  const edited = original.replace('JSX fixture', 'JSX fixture v2');
  writeFileSync(appFile, edited);
  await new Promise((r) => setTimeout(r, 2500));

  const afterHmr = readIndex();
  const hmrButton = findButton(afterHmr);
  const attrHmr = await browser.evaluate<string | null>(
    "document.querySelector('#submit-btn')?.getAttribute('data-kiln-id') ?? null",
  );
  const textHmr = await browser.evaluate<string | null>(
    "document.querySelector('h1')?.textContent ?? null",
  );

  field('', '');
  field('after HMR id', hmrButton?.id);
  field('after HMR line', `${hmrButton?.line} (truth ${truthLineOf(edited)})`);
  field('after HMR dom id', attrHmr);
  field('after HMR heading', textHmr);

  // Full rewrite: the model replaces the file rather than nudging it.
  const rewritten = `// regenerated by the agent\nexport function App() {\n  return (\n    <main className="app">\n      <h1>JSX fixture v3</h1>\n      <section className="panel">\n        <button id="submit-btn" className="primary">\n          Send\n        </button>\n      </section>\n    </main>\n  );\n}\n`;
  writeFileSync(appFile, rewritten);
  await new Promise((r) => setTimeout(r, 2500));

  const afterRewrite = readIndex();
  const rewriteButton = findButton(afterRewrite);
  const attrRewrite = await browser.evaluate<string | null>(
    "document.querySelector('#submit-btn')?.getAttribute('data-kiln-id') ?? null",
  );
  const textRewrite = await browser.evaluate<string | null>(
    "document.querySelector('#submit-btn')?.textContent?.trim() ?? null",
  );
  const staleIds = afterRewrite.elements.filter((e) => firstButton && e.id === firstButton.id);
  const resolved = afterRewrite.elements.find((e) => e.id === attrRewrite);
  const allFiles = [...new Set(afterRewrite.elements.map((e) => e.file))].map((f) => f.split('/').slice(-2).join('/'));

  field('', '');
  field('after rewrite id', rewriteButton?.id);
  field('after rewrite line', `${rewriteButton?.line} (truth ${truthLineOf(rewritten)})`);
  field('after rewrite dom id', attrRewrite);
  field('after rewrite button text', textRewrite);
  field('that id resolves to', resolved ? `${resolved.tag}#${resolved.attributes.id ?? ''}` : '(nothing)');
  field('old id now resolves to', staleIds.length ? `${staleIds[0]!.tag}@${staleIds[0]!.line}` : '(nothing)');
  field('files in index', allFiles);
  field('index grew monotonically', afterRewrite.version > first.version);

  const injectedThroughout = attrFirst === firstButton?.id && attrHmr === hmrButton?.id && attrRewrite === rewriteButton?.id;
  const linesCorrect = [firstButton, hmrButton, rewriteButton].every((e) => e && e.line === truthLineOf(
    e === firstButton ? original : e === hmrButton ? edited : rewritten,
  ));
  // The product invariant: whatever id the DOM carries must resolve back to the
  // element the user is looking at, and a pre-rewrite id must not resolve to a
  // different element that happens to sit at the same coordinates.
  const rewroteCorrectly =
    attrRewrite === rewriteButton?.id &&
    textRewrite === 'Send' &&
    resolved?.attributes.id === 'submit-btn' &&
    resolved?.tag === 'button' &&
    staleIds.length === 0;
  log('');
  field('ids present in DOM throughout', injectedThroughout);
  field('index lines always correct', linesCorrect);
  field('rewrite fully re-derived', rewroteCorrectly);

  const ok = injectedThroughout && linesCorrect && rewroteCorrectly;
  verdict(ok, 'm0.10 T1 transform-time ids survive HMR and full rewrite');
  process.exit(ok ? 0 : 1);
} finally {
  restore();
  await browser?.close();
  await proxy?.close();
  server?.stop();
  clientServer.close();
}
