import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { field, log, verdict } from './harness.ts';
import { History, git } from '../project/history.ts';
import { Remote, summariseBranch } from '../project/remote.ts';
import { detectPublish, writeDockerfile } from '../runtime/publish.ts';

const root = await mkdtemp(join(tmpdir(), 'kiln-git-'));
const work = join(root, 'project');
const origin = join(root, 'origin.git');

let ok = false;
try {
  await mkdir(work, { recursive: true });
  await git(['init', '--bare', '-q', origin], root);

  const history = new History(work);
  await history.init();
  await writeFile(join(work, 'app.js'), 'console.log("v1");\n');
  await history.commit({ promptUuid: 'p1', message: 'Add the app', costUsd: 0.1 });
  await writeFile(join(work, 'app.js'), 'console.log("v2");\n');
  await history.commit({ promptUuid: 'p2', message: 'Make it log v2', costUsd: 0.2 });

  const remote = new Remote(work, history.branch);
  const before = await remote.status();
  field('remote configured', before.configured);
  field('branch', before.branch);

  await remote.connect(origin);
  const connected = await remote.status();
  field('url after connect', connected.url?.startsWith(root) ? 'local bare repo' : String(connected.url));

  const push = await remote.push();
  field('pushed', push.pushed);
  field('branch pushed', push.branch);

  const remoteLog = (await git(['log', '--oneline', 'origin/kiln'], work)).trim();
  const commitsOnOrigin = remoteLog.split('\n').filter(Boolean).length;
  field('commits on origin', commitsOnOrigin);

  const after = await remote.status();
  field('upstream', after.upstream ?? '(none)');
  field('ahead', after.ahead);
  field('behind', after.behind);

  // A pull request body has to be useful, not a wall of diff.
  await writeFile(join(work, 'extra.css'), 'body { color: red }\n');
  await history.commit({ promptUuid: 'p3', message: 'Style it', costUsd: 0 });
  const summary = await summariseBranch(work, 'origin/kiln', 'kiln');
  field('pr title', summary.title);
  field('pr lists files', summary.body.includes('extra.css'));
  field('pr lists commits', summary.body.includes('Style it'));

  // Restore still works with a remote attached.
  const checkpoints = await history.log();
  await history.restore(checkpoints[0]!.id);
  const restored = (await readFile(join(work, 'app.js'), 'utf8')).trim();
  field('restore with remote attached', restored);

  // Publish detection.
  await writeFile(
    join(work, 'package.json'),
    JSON.stringify({ name: 'p', scripts: { dev: 'vite', build: 'vite build' }, dependencies: { react: '18' } }),
  );
  const target = await detectPublish(work);
  field('publish target', `${target.kind} (${target.label})`);
  const dockerfile = target.dockerfile ? await writeDockerfile(work, target.dockerfile) : null;
  const dockerfileText = dockerfile ? await readFile(dockerfile, 'utf8') : '';
  field('dockerfile written', dockerfile !== null && dockerfileText.startsWith('# Generated by kiln'));
  field('multi-stage build', dockerfileText.includes('AS build'));

  const again = await detectPublish(work);
  field('idempotent', again.kind === 'container');

  ok =
    connected.configured &&
    push.pushed &&
    commitsOnOrigin === 2 &&
    after.upstream !== null &&
    after.ahead === 0 &&
    summary.body.includes('extra.css') &&
    restored === 'console.log("v1");' &&
    dockerfile !== null;

  log('');
  verdict(ok, 'm3 git remote: connect, push, upstream tracking, pr summary, publish scaffold');
} finally {
  await rm(root, { recursive: true, force: true });
}

process.exit(ok ? 0 : 1);
